# Generated by Django 4.2.4 on 2024-02-28 16:30

from django.db import migrations, models
import django.db.models.deletion
import products.models.models_product


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produto')),
                ('company_name', models.CharField(blank=True, help_text='Exemplo: Amazon, Aliexpress', max_length=255, null=True, verbose_name='Nome da empresa que o produto faz parte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço')),
                ('affiliate_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link de afilidado')),
                ('coupon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cupom')),
                ('favorite', models.BooleanField(blank=True, default=False, null=True, verbose_name='Favorito')),
                ('image', models.FileField(blank=True, help_text='A dimensão da imagem deve ser 160x160', null=True, upload_to=products.models.models_product.product_image_path, verbose_name='Imagem')),
                ('is_video', models.BooleanField(blank=True, default=False, null=True, verbose_name='É vídeo?')),
                ('resend_product', models.BooleanField(blank=True, default=False, null=True, verbose_name='Reenviar produto para os grupos?')),
                ('product_slider', models.BooleanField(blank=True, default=False, null=True, verbose_name='Slider')),
                ('image_product_slider', models.ImageField(blank=True, help_text='A dimensão da imagem deve ser 1170x480', null=True, upload_to='', verbose_name='Imagem do slider')),
                ('product_description', models.TextField(blank=True, default='✅{titulo}✅\n                                               \n\n🔥 R${preco}\n                                               \n🔖 Use o cupom: {cupom}\n                                               \n\n🛍 Compre aqui: {link_produto}\n                                               \n😄 Convide seus amigos e familiares para participarem dos nossos grupos de promoção: {link_do_grupo}\n                                               \n⚠O link da foto na promo, Não está Clicável ? É só adicionar um dos ADMS em\xa0seus\xa0contatos', help_text='Alem das informações princioais, digite aqui outra informação que deseja enviar: Use o modelo descrito como base', null=True, verbose_name='Descrição para envio da mensagem')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category', verbose_name='Categoria')),
                ('company_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.productstore', verbose_name='Shop online do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
