# Generated by Django 4.2.4 on 2024-02-28 17:00

from django.db import migrations, models
import products.models.models_product


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_product_slider',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_slider',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, help_text='A dimensão da imagem deve ser 160x160', max_length=250, null=True, upload_to=products.models.models_product.product_image_path, verbose_name='Imagem'),
        ),
    ]
