# Generated by Django 4.2.4 on 2024-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_slug_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, default='✅{titulo}✅\n                                               \n\n🔥 R${preco}\n                                               \n🔖 Use o cupom: {cupom}\n                                               \n🛍 Compre aqui: {link_produto}\n                                               \n\n😄 Convide seus amigos e familiares para participarem dos nossos grupos de promoção: {link_do_grupo}\n                                               \n⚠ O link da foto na promo, Não está Clicável ? É só adicionar um dos ADMS em seus contatos', help_text='Alem das informações princioais, digite aqui outra informação que deseja enviar: Use o modelo descrito como base', null=True, verbose_name='Descrição para envio da mensagem'),
        ),
    ]
