# Generated by Django 4.2.4 on 2024-03-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, default=b'\xe2\x9c\x85{titulo}\xe2\x9c\x85\n\n                                               \xf0\x9f\x94\xa5 R${preco}\n                                               \xf0\x9f\x94\x96 Use o cupom: {cupom}\n                                               \xf0\x9f\x9b\x8d Compre aqui: {link_produto}\n                                               \n\xf0\x9f\x98\x84 Convide seus amigos e familiares para participarem dos nossos grupos de promo\xc3\xa7\xc3\xa3o: {link_do_grupo}\n                                               \n\xe2\x9a\xa0 O link da foto na promo, N\xc3\xa3o est\xc3\xa1 Clic\xc3\xa1vel? \xc3\x89 s\xc3\xb3 adicionar um dos ADMS em seus contatos', help_text='Alem das informações princioais, digite aqui outra informação que deseja enviar: Use o modelo descrito como base', null=True, verbose_name='Descrição para envio da mensagem'),
        ),
    ]
