# Generated by Django 4.2.4 on 2024-03-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_favoriteproductlink_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='favoriteproductlink',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product', verbose_name='Produto'),
        ),
    ]
