# Generated by Django 4.2.4 on 2024-03-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='is_liked',
        ),
    ]
