# Generated by Django 4.2.9 on 2024-01-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, help_text='Verificar se o usuário é uma empresa ou um usuário comun', verbose_name='Empresa'),
        ),
    ]
