# Generated by Django 5.0.2 on 2024-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_charisma',
        ),
        migrations.AddField(
            model_name='user',
            name='user_system',
            field=models.BooleanField(default=False, help_text='Usuário funcionário da empresa.', verbose_name='Usuário do sistema'),
        ),
    ]
