# Generated by Django 4.2.4 on 2024-02-28 16:49

from django.db import migrations, models
import helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='image',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=helpers.utils.image_company_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='image_aba',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=helpers.utils.image_company_path, verbose_name='Imagem da aba'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='offer_group',
            field=models.URLField(blank=True, max_length=2500, null=True, verbose_name='URL grupo de ofertas principal'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='send_product_description',
            field=models.TextField(blank=True, default='✅{titulo}✅\n                                               \n\n🔥 R${preco}\n                                               \n🔖 Use o cupom: {cupom}\n                                               \n🛍 Compre aqui: {link_produto}\n                                               \n\n😄 Convide seus amigos e familiares para participarem dos nossos grupos de promoção: {link_do_grupo}\n                                               \n⚠O link da foto na promo, Não está Clicável ? É só adicionar um dos ADMS em\xa0seus\xa0contatos', help_text='Alem das informações princioais, digite aqui outra informação que deseja enviar: Use o modelo descrito como base', null=True, verbose_name='Descrição para envio da mensagem'),
        ),
    ]
