# Generated by Django 4.2.4 on 2024-03-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_configmodel_image_alter_configmodel_image_aba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='offer_group',
        ),
        migrations.AddField(
            model_name='configmodel',
            name='telegram_channel',
            field=models.URLField(blank=True, max_length=2500, null=True, verbose_name='Grupo de ofertas principal Telegram'),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='whatsapp_group',
            field=models.URLField(blank=True, max_length=2500, null=True, verbose_name='Grupo de ofertas principal Whatsapp'),
        ),
        migrations.AddField(
            model_name='configmodel',
            name='whatsapp_support',
            field=models.URLField(blank=True, max_length=2500, null=True, verbose_name='Contato Whatsapp para Suporte'),
        ),
    ]
