# Generated by Django 4.2.4 on 2024-02-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do anuncio')),
                ('tag_meta_ads', models.TextField(blank=True, help_text='Modelo do script meta: <meta name="google-adsense-account" content="ca-pub-9679651013955080">', max_length=2000, null=True, verbose_name='Script Meta do anuncio')),
                ('script_ads', models.TextField(blank=True, help_text='Modelo do script: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6546541654615615151" crossorigin="anonymous"></script>', max_length=2000, null=True, verbose_name='Script do anuncio')),
                ('ads_txt', models.FileField(blank=True, help_text='ads.txt é um arquivo txt que o google ads pede para adicionar, um dos formato: google.com, pub-9679651013955080, DIRECT, f08c47fec0942fa5', null=True, upload_to='', verbose_name='Importar ads.txt')),
            ],
            options={
                'verbose_name': 'Configuração ADS',
                'verbose_name_plural': 'Configurações ADS',
            },
        ),
    ]
