# Generated by Django 4.2.4 on 2024-02-28 15:55

from django.db import migrations, models
import helpers.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(blank=True, help_text='Exemplo: Aliexpress, Shopee, Amazon, Mercado Livre...', max_length=200, null=True, verbose_name='Nome da empresa')),
                ('image', models.ImageField(blank=True, help_text='A dimensão da imagem deve ser 160x160', null=True, upload_to=helpers.utils.image_company_path, verbose_name='Imagem da empresa')),
            ],
            options={
                'verbose_name': 'Loja do produto',
                'verbose_name_plural': 'Lojas dos produtos',
            },
        ),
    ]
