# Generated by Django 4.2.4 on 2024-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='alug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Nome a exibir na URL (Slug)'),
        ),
    ]
