# Generated by Django 4.2.4 on 2024-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_productstore_alug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='alug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Nome a exibir na URL (Slug)'),
        ),
    ]
