# Generated by Django 4.2.4 on 2024-03-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_productstore_alug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstore',
            old_name='alug',
            new_name='slug',
        ),
    ]
